services:
  aws-cli:
    build: .
    container_name: aws-cli
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json